generatorName: python
typeMappings: {}
additionalProperties:
  packageName: hellosign_sdk
  projectName: hellosign-python-sdk
  sortModelPropertiesByRequiredFlag: true
files:
  event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: hellosign_sdk/event_callback_helper.py
globalProperties:
  apiTests: false
  modelTests: false
